export type {
  HeroBackgroundMode,
  HeroContentAlign,
  HeroHorizontalPosition,
  HeroHotspot,
  HeroHotspotAnchor,
  HeroHotspotTarget,
  HeroImageFit,
  HeroLayerId,
  HeroLayerModel,
  HeroLayoutMode,
  HeroProductPlacement,
  HeroProductPresence,
  HeroSecondaryProductPreset,
  HeroSlideLayerFields,
  HeroSlideUpdates,
  HeroSlideUpdateValue,
  HeroStyleInput,
  HeroStylePayload,
  HeroTextSize,
  HeroVerticalPosition,
} from "./hero-types";

export {
  DEFAULT_HERO_LAYER_MODEL,
  DEFAULT_HERO_PRODUCTS,
  HERO_BACKGROUND_MODE_OPTIONS,
  HERO_CONTENT_OFFSET,
  HERO_HOTSPOT_ANCHOR_COORDINATES,
  HERO_HOTSPOT_ANCHOR_OPTIONS,
  HERO_HOTSPOT_TARGET_OPTIONS,
  HERO_PRODUCT_OFFSET,
  HERO_PRODUCT_PLACEMENT_OPTIONS,
  HERO_PRODUCT_PRESENCE_DEFAULTS,
  HERO_PRODUCT_PRESENCE_OPTIONS,
  HERO_PRODUCT_SCALE,
  HERO_SECONDARY_PRODUCT_PRESET_OPTIONS,
  HERO_TEXT_SIZE_OPTIONS,
} from "./hero-defaults";

export {
  clampHeroContentOffset,
  clampHeroHotspotCoordinate,
  clampHeroProductOffset,
  clampHeroProductScale,
  clampOverlayOpacity,
  createNextHeroHotspotId,
  normalizeHeroHotspots,
  normalizeHeroSlide,
  toFlatHeroVariables,
  toHeroLayerModel,
  updateHeroLayerModel,
  updateHeroSlideLayer,
} from "./hero-normalization";
