-- Fail-closed contract verification for the shipping location catalog.
-- Mirrors verify-ecommerce-contract.sql's style (schema/column/constraint
-- assertions by name, `raise exception` on failure); later shipping slices
-- extend this file rather than replacing it (D20).

-- -----------------------------------------------------------------------------
-- D1: the table exists.
-- -----------------------------------------------------------------------------
do $$
begin
  if to_regclass('ecommerce.co_locations') is null then
    raise exception 'Missing ecommerce.co_locations';
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- D2/D30: the Divipola key shape (department + municipality, code and name)
-- plus the surrogate id a later shipping_location_id FK will reference.
-- -----------------------------------------------------------------------------
do $$
declare
  v_missing text[];
begin
  select array_agg(required_column order by required_column) into v_missing
  from (values
    ('id'), ('department_code'), ('department_name'),
    ('municipality_code'), ('municipality_name'), ('municipality_type'),
    ('longitude'), ('latitude'), ('created_at'), ('updated_at')
  ) req(required_column)
  where not exists (
    select 1 from information_schema.columns c
    where c.table_schema = 'ecommerce' and c.table_name = 'co_locations' and c.column_name = req.required_column
  );

  if v_missing is not null then
    raise exception 'Missing ecommerce.co_locations columns: %', array_to_string(v_missing, ', ');
  end if;
end $$;

-- pg_attribute.attnotnull over information_schema.columns.is_nullable: the
-- latter is the 'YES'/'NO' yes_or_no domain (uppercase, unlike every other
-- lowercase literal this file compares against), which is exactly the
-- case-sensitive trap that made this block raise unconditionally, against
-- every database, schema-correct or not. attnotnull is a plain boolean, so
-- there's no case to get wrong.
do $$
declare
  v_missing text[];
begin
  select array_agg(required_column order by required_column) into v_missing
  from (values
    ('department_code'), ('department_name'),
    ('municipality_code'), ('municipality_name'), ('municipality_type')
  ) req(required_column)
  where not exists (
    select 1 from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'co_locations'
      and a.attname = req.required_column
      and a.attnum > 0
      and not a.attisdropped
      and a.attnotnull
  );

  if v_missing is not null then
    raise exception 'ecommerce.co_locations columns must be NOT NULL: %', array_to_string(v_missing, ', ');
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- D2: keyed on (department_code, municipality_code) -- the pair Divipola
-- itself is keyed on, named explicitly in the migration so it can be checked
-- by name here instead of relying on Postgres' autogenerated default.
-- -----------------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'co_locations'
      and con.conname = 'co_locations_department_municipality_key'
      and con.contype = 'u'
  ) then
    raise exception 'Missing unique constraint ecommerce.co_locations_department_municipality_key on (department_code, municipality_code)';
  end if;

  if not exists (
    select 1 from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'co_locations' and con.contype = 'p'
  ) then
    raise exception 'ecommerce.co_locations is missing a primary key';
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- D27: RLS enabled, and the grant contract by role -- anon/authenticated get
-- SELECT and nothing else, service_role keeps full access. Same posture as
-- the email platform tables' contract (has_table_privilege catalog checks).
-- -----------------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'co_locations' and c.relrowsecurity is true
  ) then
    raise exception 'ecommerce.co_locations is missing enabled RLS';
  end if;
end $$;

do $$
declare
  v_violations text[];
begin
  select array_agg(msg) into v_violations
  from (
    select format('%s does not have SELECT on ecommerce.co_locations', role) as msg
    from unnest(array['anon', 'authenticated']) role
    where not has_table_privilege(role, 'ecommerce.co_locations', 'select')
    union all
    select format('%s has %s on ecommerce.co_locations', role, priv)
    from unnest(array['anon', 'authenticated']) role
    cross join unnest(array['insert', 'update', 'delete']) priv
    where has_table_privilege(role, 'ecommerce.co_locations', priv)
  ) v;

  if v_violations is not null then
    raise exception 'ecommerce.co_locations grant contract broken: %', array_to_string(v_violations, '; ');
  end if;

  if not (
    has_table_privilege('service_role', 'ecommerce.co_locations', 'select')
    and has_table_privilege('service_role', 'ecommerce.co_locations', 'insert')
    and has_table_privilege('service_role', 'ecommerce.co_locations', 'update')
  ) then
    raise exception 'service_role must retain full access to ecommerce.co_locations';
  end if;
end $$;

-- Live-role reproduction: has_table_privilege proves the catalog is right,
-- only an actual query under SET LOCAL ROLE proves what PostgREST's own anon
-- role really sees once RLS is folded in (same reasoning as the email
-- platform contract's finalize-profile-requires-service-role block).
do $$
declare
  v_count integer;
begin
  set local role anon;
  select count(*) into v_count from ecommerce.co_locations where department_code = '05' limit 1;
  reset role;

  if v_count = 0 then
    raise exception 'anon must be able to SELECT ecommerce.co_locations (public DANE data)';
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- Data: the actual DANE Divipola catalog, not just an empty shell -- 33
-- departments, 1,122 municipios, matching this slice's own goal.
-- -----------------------------------------------------------------------------
do $$
declare
  v_row_count integer;
  v_department_count integer;
begin
  select count(*), count(distinct department_code) into v_row_count, v_department_count
  from ecommerce.co_locations;

  if v_row_count <> 1122 then
    raise exception 'Expected 1122 municipios seeded in ecommerce.co_locations, found %', v_row_count;
  end if;

  if v_department_count <> 33 then
    raise exception 'Expected 33 distinct departments in ecommerce.co_locations, found %', v_department_count;
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- Finding 1 (design audit, plan-envios-ecommerce): ecommerce.co_departments
-- is a real departments source, not co_locations deduplicated in application
-- memory -- PostgREST's own max_rows cap (supabase/config.toml) truncates a
-- 1,122-row co_locations response before every department reaches the
-- picker. 33 rows can never collide with a 1,000-row cap. D27: same
-- public-read / closed-to-write posture as co_locations itself.
-- -----------------------------------------------------------------------------
do $$
begin
  if to_regclass('ecommerce.co_departments') is null then
    raise exception 'Missing ecommerce.co_departments';
  end if;
end $$;

do $$
declare
  v_violations text[];
begin
  select array_agg(msg) into v_violations
  from (
    select format('%s does not have SELECT on ecommerce.co_departments', role) as msg
    from unnest(array['anon', 'authenticated']) role
    where not has_table_privilege(role, 'ecommerce.co_departments', 'select')
    union all
    select format('%s has %s on ecommerce.co_departments', role, priv)
    from unnest(array['anon', 'authenticated']) role
    cross join unnest(array['insert', 'update', 'delete']) priv
    where has_table_privilege(role, 'ecommerce.co_departments', priv)
  ) v;

  if v_violations is not null then
    raise exception 'ecommerce.co_departments grant contract broken: %', array_to_string(v_violations, '; ');
  end if;

  if not has_table_privilege('service_role', 'ecommerce.co_departments', 'select') then
    raise exception 'service_role must retain SELECT on ecommerce.co_departments';
  end if;
end $$;

-- The view must actually return every department, not just exist -- this is
-- the assertion that would have caught Finding 1 directly: a co_departments
-- built as anything other than a real distinct projection (e.g. a
-- reintroduced in-memory dedupe upstream) could still under-count here.
do $$
declare
  v_department_count integer;
begin
  select count(*) into v_department_count from ecommerce.co_departments;

  if v_department_count <> 33 then
    raise exception 'Expected 33 departments in ecommerce.co_departments, found %', v_department_count;
  end if;
end $$;

-- security_invoker so this view runs under the QUERYING role's own RLS, not
-- the view owner's -- the same posture ecommerce.co_departments' own
-- migration (20260807000700) claims for itself. pg_class.reloptions is what
-- actually proves the WITH (security_invoker = true) clause landed; a view
-- recreated without it would still pass every assertion above while running
-- as owner.
do $$
begin
  if not exists (
    select 1 from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'co_departments'
      and c.reloptions @> array['security_invoker=true']
  ) then
    raise exception 'ecommerce.co_departments must be security_invoker=true';
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- D4/D7/D27 (slice S2, 20260807000200): store_shipping_settings -- the table
-- itself is only proven to exist by verify-ecommerce-contract.sql's generic
-- table sweep. Its RLS posture, its anon-closed grant contract (same D27
-- posture as the zones/rates tables below) and the mode CHECK constraint are
-- this file's to assert.
-- -----------------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'store_shipping_settings' and c.relrowsecurity is true
  ) then
    raise exception 'ecommerce.store_shipping_settings is missing enabled RLS';
  end if;
end $$;

do $$
declare
  v_violations text[];
begin
  select array_agg(msg) into v_violations
  from (
    select format('anon has %s on ecommerce.store_shipping_settings', priv) as msg
    from unnest(array['select', 'insert', 'update', 'delete']) priv
    where has_table_privilege('anon', 'ecommerce.store_shipping_settings', priv)
  ) v;

  if v_violations is not null then
    raise exception 'anon must have no access to ecommerce.store_shipping_settings: %', array_to_string(v_violations, '; ');
  end if;

  if exists (
    select 1
    from unnest(array['select', 'insert', 'update', 'delete']) priv
    where not has_table_privilege('service_role', 'ecommerce.store_shipping_settings', priv)
  ) then
    raise exception 'service_role must retain full access to ecommerce.store_shipping_settings';
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    join pg_attribute a on a.attrelid = c.oid and a.attnum = any(con.conkey)
    where n.nspname = 'ecommerce' and c.relname = 'store_shipping_settings'
      and con.contype = 'c' and a.attname = 'mode'
  ) then
    raise exception 'Missing CHECK constraint on ecommerce.store_shipping_settings.mode';
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- D8/A14 (20260807000300): weight_grams's own non-negativity constraints,
-- named "so a future contract check can assert them by name" per that
-- migration's own comment -- this is that check.
-- -----------------------------------------------------------------------------
do $$
declare
  v_missing text[];
begin
  select array_agg(required_constraint order by required_constraint) into v_missing
  from (values
    ('store_items', 'store_items_weight_grams_nonnegative_chk'),
    ('item_variants', 'item_variants_weight_grams_nonnegative_chk')
  ) req(required_table, required_constraint)
  where not exists (
    select 1 from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = req.required_table
      and con.conname = req.required_constraint and con.contype = 'c'
  );

  if v_missing is not null then
    raise exception 'Missing named CHECK constraints for weight_grams: %', array_to_string(v_missing, ', ');
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- D2/D30 (20260807000400): ecommerce.orders.shipping_location_id, its ON
-- DELETE RESTRICT foreign key to co_locations, and the frozen department
-- columns a later shipping-zone lookup and every order-detail reader depend
-- on existing without a join back to co_locations.
-- -----------------------------------------------------------------------------
do $$
declare
  v_missing text[];
begin
  select array_agg(required_column order by required_column) into v_missing
  from (values
    ('shipping_location_id'), ('shipping_department_code'),
    ('shipping_department_name'), ('shipping_municipality_code')
  ) req(required_column)
  where not exists (
    select 1 from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'orders' and a.attname = req.required_column
      and a.attnum > 0 and not a.attisdropped
  );

  if v_missing is not null then
    raise exception 'Missing frozen shipping destination columns on ecommerce.orders: %', array_to_string(v_missing, ', ');
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    join pg_class fc on fc.oid = con.confrelid
    join pg_namespace fn on fn.oid = fc.relnamespace
    join pg_attribute a on a.attrelid = c.oid and a.attnum = any(con.conkey)
    where n.nspname = 'ecommerce' and c.relname = 'orders'
      and con.contype = 'f'
      and a.attname = 'shipping_location_id'
      and fn.nspname = 'ecommerce' and fc.relname = 'co_locations'
      and con.confdeltype = 'r'
  ) then
    raise exception 'Missing ON DELETE RESTRICT foreign key from ecommerce.orders.shipping_location_id to ecommerce.co_locations';
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- D3/D5/D6/D27 (slice S7): shipping_zones, shipping_zone_destinations and
-- shipping_rates exist and are RLS-enabled, closed to anon.
-- -----------------------------------------------------------------------------
do $$
begin
  if to_regclass('ecommerce.shipping_zones') is null then
    raise exception 'Missing ecommerce.shipping_zones';
  end if;
  if to_regclass('ecommerce.shipping_zone_destinations') is null then
    raise exception 'Missing ecommerce.shipping_zone_destinations';
  end if;
  if to_regclass('ecommerce.shipping_rates') is null then
    raise exception 'Missing ecommerce.shipping_rates';
  end if;
end $$;

do $$
declare
  v_missing text[];
begin
  select array_agg(required_column order by required_column) into v_missing
  from (values
    ('shipping_zones', 'store_id'), ('shipping_zones', 'name'),
    ('shipping_zone_destinations', 'zone_id'), ('shipping_zone_destinations', 'store_id'),
    ('shipping_zone_destinations', 'department_code'),
    ('shipping_rates', 'zone_id'), ('shipping_rates', 'basis'), ('shipping_rates', 'amount')
  ) req(required_table, required_column)
  where not exists (
    select 1 from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = req.required_table
      and a.attname = req.required_column
      and a.attnum > 0
      and not a.attisdropped
      and a.attnotnull
  );

  if v_missing is not null then
    raise exception 'Missing NOT NULL columns on shipping zones/rates tables: %', array_to_string(v_missing, ', ');
  end if;
end $$;

-- D3: at most one zone per store may claim a given destination -- the
-- department-only and municipio partial unique indexes, plus the composite
-- FK that keeps a destination's store_id honest against its owning zone.
do $$
begin
  if not exists (
    select 1 from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'shipping_zone_destinations'
      and con.conname = 'shipping_zone_destinations_zone_store_fk' and con.contype = 'f'
  ) then
    raise exception 'Missing ecommerce.shipping_zone_destinations_zone_store_fk';
  end if;

  if not exists (
    select 1 from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'shipping_zone_destinations'
      and con.conname = 'shipping_zone_destinations_municipality_fk' and con.contype = 'f'
  ) then
    raise exception 'Missing ecommerce.shipping_zone_destinations_municipality_fk';
  end if;

  -- pg_indexes proves the name exists but not what kind of index it is -- a
  -- non-unique, non-partial index of the same name would pass a name-only
  -- check. pg_index.indisunique/indpred (partial indexes carry a predicate,
  -- a full index has none) are what actually prove "at most one zone per
  -- store may claim this destination" is enforced, not just indexed.
  if not exists (
    select 1
    from pg_index i
    join pg_class ic on ic.oid = i.indexrelid
    join pg_class tc on tc.oid = i.indrelid
    join pg_namespace n on n.oid = tc.relnamespace
    where n.nspname = 'ecommerce' and tc.relname = 'shipping_zone_destinations'
      and ic.relname = 'shipping_zone_destinations_department_key'
      and i.indisunique and i.indpred is not null
  ) then
    raise exception 'ecommerce.shipping_zone_destinations_department_key must be a UNIQUE partial index';
  end if;

  if not exists (
    select 1
    from pg_index i
    join pg_class ic on ic.oid = i.indexrelid
    join pg_class tc on tc.oid = i.indrelid
    join pg_namespace n on n.oid = tc.relnamespace
    where n.nspname = 'ecommerce' and tc.relname = 'shipping_zone_destinations'
      and ic.relname = 'shipping_zone_destinations_municipality_key'
      and i.indisunique and i.indpred is not null
  ) then
    raise exception 'ecommerce.shipping_zone_destinations_municipality_key must be a UNIQUE partial index';
  end if;
end $$;

-- D6: basis is constrained to the three known values, and a row's bounds
-- must match its basis (flat carries none, ranged rows require range_from).
do $$
begin
  if not exists (
    select 1 from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'shipping_rates'
      and con.conname = 'shipping_rates_basis_chk' and con.contype = 'c'
  ) then
    raise exception 'Missing ecommerce.shipping_rates_basis_chk';
  end if;

  if not exists (
    select 1 from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'shipping_rates'
      and con.conname = 'shipping_rates_bounds_match_basis_chk' and con.contype = 'c'
  ) then
    raise exception 'Missing ecommerce.shipping_rates_bounds_match_basis_chk';
  end if;

  if not exists (
    select 1 from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'shipping_rates'
      and con.conname = 'shipping_rates_amount_nonnegative_chk' and con.contype = 'c'
  ) then
    raise exception 'Missing ecommerce.shipping_rates_amount_nonnegative_chk';
  end if;
end $$;

-- D27: RLS enabled on all three, and closed to anon entirely -- the checkout
-- quote (a later slice) reads through service_role, never anon/authenticated
-- directly, same posture as store_shipping_settings.
do $$
declare
  v_missing_rls text[];
begin
  select array_agg(t order by t) into v_missing_rls
  from unnest(array['shipping_zones', 'shipping_zone_destinations', 'shipping_rates']) t
  where not exists (
    select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = t and c.relrowsecurity is true
  );

  if v_missing_rls is not null then
    raise exception 'Missing enabled RLS on: %', array_to_string(v_missing_rls, ', ');
  end if;
end $$;

do $$
declare
  v_violations text[];
begin
  select array_agg(msg) into v_violations
  from (
    select format('anon has %s on ecommerce.%s', priv, tbl) as msg
    from unnest(array['shipping_zones', 'shipping_zone_destinations', 'shipping_rates']) tbl
    cross join unnest(array['select', 'insert', 'update', 'delete']) priv
    where has_table_privilege('anon', format('ecommerce.%s', tbl), priv)
  ) v;

  if v_violations is not null then
    raise exception 'anon must have no access to shipping zones/rates tables: %', array_to_string(v_violations, '; ');
  end if;

  if exists (
    select 1
    from unnest(array['shipping_zones', 'shipping_zone_destinations', 'shipping_rates']) tbl
    cross join unnest(array['select', 'insert', 'update', 'delete']) priv
    where not has_table_privilege('service_role', format('ecommerce.%s', tbl), priv)
  ) then
    raise exception 'service_role must retain full access to shipping zones/rates tables';
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- D23 (slice S9): ecommerce.orders.shipping_status exists and is constrained
-- to the four resolver outcomes (A3, stored English).
-- -----------------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from information_schema.columns c
    where c.table_schema = 'ecommerce' and c.table_name = 'orders' and c.column_name = 'shipping_status'
  ) then
    raise exception 'Missing ecommerce.orders.shipping_status';
  end if;

  if not exists (
    select 1 from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'orders'
      and con.conname = 'orders_shipping_status_chk' and con.contype = 'c'
  ) then
    raise exception 'Missing ecommerce.orders_shipping_status_chk';
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- D26: shipping_cost/tax_amount/discount_amount are NOT NULL (pg_attribute.
-- attnotnull, never information_schema.is_nullable -- its 'YES'/'NO' domain
-- is the exact case-sensitive trap the co_locations block above documents).
-- A nullable money column would let a raw insert dodge the coherence check
-- below via NULL's three-valued logic (a CHECK only fails on an explicit
-- false, never on unknown).
-- -----------------------------------------------------------------------------
do $$
declare
  v_missing text[];
begin
  select array_agg(required_column order by required_column) into v_missing
  from (values ('subtotal'), ('shipping_cost'), ('tax_amount'), ('discount_amount'), ('total_amount')) req(required_column)
  where not exists (
    select 1 from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'orders'
      and a.attname = req.required_column
      and a.attnum > 0
      and not a.attisdropped
      and a.attnotnull
  );

  if v_missing is not null then
    raise exception 'ecommerce.orders money columns must be NOT NULL: %', array_to_string(v_missing, ', ');
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- D26: non-negativity on every money column, and the one named constraint
-- this whole slice exists for -- total_amount must equal its own components.
-- -----------------------------------------------------------------------------
do $$
declare
  v_missing text[];
begin
  select array_agg(required_constraint order by required_constraint) into v_missing
  from (values
    ('orders_subtotal_nonnegative_chk'), ('orders_shipping_cost_nonnegative_chk'),
    ('orders_tax_amount_nonnegative_chk'), ('orders_discount_amount_nonnegative_chk'),
    ('orders_total_amount_nonnegative_chk'), ('orders_total_amount_matches_components_chk')
  ) req(required_constraint)
  where not exists (
    select 1 from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'orders'
      and con.conname = req.required_constraint and con.contype = 'c'
  );

  if v_missing is not null then
    raise exception 'Missing named check constraints on ecommerce.orders: %', array_to_string(v_missing, ', ');
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- A13: the coherence constraint isn't just present, it's VALIDATED -- added
-- NOT VALID by the migration (a live store's historical orders could in
-- principle diverge, see the migration's own comment) and then validated in
-- the same migration, but a constraint a validation attempt left NOT VALID
-- (a historical mismatch the operator still needs to fix) must be a visible,
-- failing fact here, not a silent assumption the existence check above
-- alone can't catch -- pg_constraint.convalidated, not information_schema.
-- -----------------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'orders'
      and con.conname = 'orders_total_amount_matches_components_chk'
      and con.contype = 'c'
      and con.convalidated
  ) then
    raise exception 'orders_total_amount_matches_components_chk exists but is NOT VALID -- some historical order diverges from total_amount = subtotal + shipping_cost + tax_amount - discount_amount; correct it and run `alter table ecommerce.orders validate constraint orders_total_amount_matches_components_chk;`';
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- D23/D26 runtime: the RPC actually threads shipping_status/shipping_cost
-- through into the inserted row, and the coherence constraint actually
-- REJECTS a mismatched total -- not just present in the catalog, enforced.
-- Wrapped in its own transaction, rolled back at the end (same shape
-- verify-email-platform-contract.sql already uses for its own runtime
-- assertions), so this script stays safe to re-run against a live stack.
-- -----------------------------------------------------------------------------
begin;

do $$
declare
  v_owner_id uuid := gen_random_uuid();
  v_store_id uuid;
  v_reserved_order_number text;
  v_notifications jsonb;
  v_result jsonb;
begin
  insert into auth.users (id, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, aud, role)
  values (v_owner_id, 'shipping-contract-check-owner@example.com', 'x', now(), now(), now(), '{}', '{}', 'authenticated', 'authenticated');
  insert into ecommerce.user_profiles (id, email, role) values (v_owner_id, 'shipping-contract-check-owner@example.com', 'user');
  v_store_id := ecommerce.provision_store('shipping-contract-check-store', 'Shipping Contract Check Store', v_owner_id, 'COP');

  v_reserved_order_number := ecommerce.generate_order_number(v_store_id);
  v_notifications := jsonb_build_array(
    jsonb_build_object(
      'templateKind', 'order-received', 'recipientEmail', 'buyer@example.com',
      'fromAddress', 'Shipping Contract Check Store vía Osoria <pedidos@mail.osoria.help>', 'replyToAddress', null,
      'subject', 'Recibimos tu pedido', 'htmlBody', '<p>h</p>', 'textBody', 't',
      'idempotencyKey', 'checkout:' || v_store_id::text || ':shipping-check-1:order-received'
    )
  );

  -- D23: a coherent order (30000 + 5000 = 35000) with an explicit
  -- shipping_status must land with BOTH columns exactly as passed -- proves
  -- the create or replace above actually reads p_order->>'shipping_status'
  -- instead of silently dropping it.
  v_result := ecommerce.create_order_with_notifications(
    v_store_id, 'shipping-check-1', 'fingerprint-shipping-check-1',
    jsonb_build_object(
      'customer_type', 'guest', 'customer_email', 'buyer@example.com',
      'customer_first_name', 'Ada', 'customer_last_name', 'Lovelace',
      'shipping_address', 'Calle 123', 'shipping_city', 'Bogotá', 'shipping_postal_code', '110111',
      'payment_method', 'cash_on_delivery', 'subtotal', 30000, 'shipping_cost', 5000,
      'shipping_status', 'rate', 'total_amount', 35000,
      'order_number', v_reserved_order_number
    ),
    jsonb_build_array(
      jsonb_build_object('product_name', 'Café 250g', 'unit_price', 30000, 'quantity', 1, 'total_price', 30000)
    ),
    v_notifications
  );

  if (v_result ->> 'ok')::boolean is not true then
    raise exception 'D23: a coherent order carrying shipping_status should have been created, got %', v_result;
  end if;
  if (v_result -> 'order' ->> 'shipping_status') is distinct from 'rate' then
    raise exception 'D23: create_order_with_notifications must thread shipping_status through into the inserted row, got %', v_result -> 'order' ->> 'shipping_status';
  end if;
  if (v_result -> 'order' ->> 'shipping_cost')::numeric is distinct from 5000::numeric then
    raise exception 'D23: create_order_with_notifications must thread shipping_cost through into the inserted row, got %', v_result -> 'order' ->> 'shipping_cost';
  end if;

  -- D26: a raw insert whose total_amount does not equal subtotal +
  -- shipping_cost + tax_amount - discount_amount (100000 + 0 + 0 - 0 =
  -- 100000, not 999999) must be rejected by the database itself, whatever
  -- wrote it -- proven by actually attempting it, not just checking the
  -- constraint's name is present in the catalog.
  begin
    insert into ecommerce.orders (store_id, order_number, customer_email, subtotal, total_amount)
    values (v_store_id, 'SHIP-CHK-INCOHERENT-1', 'buyer@example.com', 100000, 999999);
    raise exception 'D26: an order whose total_amount does not equal subtotal + shipping_cost + tax_amount - discount_amount must be rejected';
  exception when check_violation then
    null;
  end;

  if exists (select 1 from ecommerce.orders where store_id = v_store_id and order_number = 'SHIP-CHK-INCOHERENT-1') then
    raise exception 'D26: the rejected incoherent-total insert must have left no row behind';
  end if;
end $$;

rollback;

select 'shipping contract ok' as status;
