-- Fail-closed contract verification for the shipping location catalog.
-- Mirrors verify-ecommerce-contract.sql's style (schema/column/constraint
-- assertions by name, `raise exception` on failure); later shipping slices
-- extend this file rather than replacing it (D20).

-- -----------------------------------------------------------------------------
-- D1: the table exists.
-- -----------------------------------------------------------------------------
do $$
begin
  if to_regclass('ecommerce.co_locations') is null then
    raise exception 'Missing ecommerce.co_locations';
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- D2/D30: the Divipola key shape (department + municipality, code and name)
-- plus the surrogate id a later shipping_location_id FK will reference.
-- -----------------------------------------------------------------------------
do $$
declare
  v_missing text[];
begin
  select array_agg(required_column order by required_column) into v_missing
  from (values
    ('id'), ('department_code'), ('department_name'),
    ('municipality_code'), ('municipality_name'), ('municipality_type'),
    ('longitude'), ('latitude'), ('created_at'), ('updated_at')
  ) req(required_column)
  where not exists (
    select 1 from information_schema.columns c
    where c.table_schema = 'ecommerce' and c.table_name = 'co_locations' and c.column_name = req.required_column
  );

  if v_missing is not null then
    raise exception 'Missing ecommerce.co_locations columns: %', array_to_string(v_missing, ', ');
  end if;
end $$;

-- pg_attribute.attnotnull over information_schema.columns.is_nullable: the
-- latter is the 'YES'/'NO' yes_or_no domain (uppercase, unlike every other
-- lowercase literal this file compares against), which is exactly the
-- case-sensitive trap that made this block raise unconditionally, against
-- every database, schema-correct or not. attnotnull is a plain boolean, so
-- there's no case to get wrong.
do $$
declare
  v_missing text[];
begin
  select array_agg(required_column order by required_column) into v_missing
  from (values
    ('department_code'), ('department_name'),
    ('municipality_code'), ('municipality_name'), ('municipality_type')
  ) req(required_column)
  where not exists (
    select 1 from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'co_locations'
      and a.attname = req.required_column
      and a.attnum > 0
      and not a.attisdropped
      and a.attnotnull
  );

  if v_missing is not null then
    raise exception 'ecommerce.co_locations columns must be NOT NULL: %', array_to_string(v_missing, ', ');
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- D2: keyed on (department_code, municipality_code) -- the pair Divipola
-- itself is keyed on, named explicitly in the migration so it can be checked
-- by name here instead of relying on Postgres' autogenerated default.
-- -----------------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'co_locations'
      and con.conname = 'co_locations_department_municipality_key'
      and con.contype = 'u'
  ) then
    raise exception 'Missing unique constraint ecommerce.co_locations_department_municipality_key on (department_code, municipality_code)';
  end if;

  if not exists (
    select 1 from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'co_locations' and con.contype = 'p'
  ) then
    raise exception 'ecommerce.co_locations is missing a primary key';
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- D27: RLS enabled, and the grant contract by role -- anon/authenticated get
-- SELECT and nothing else, service_role keeps full access. Same posture as
-- the email platform tables' contract (has_table_privilege catalog checks).
-- -----------------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'co_locations' and c.relrowsecurity is true
  ) then
    raise exception 'ecommerce.co_locations is missing enabled RLS';
  end if;
end $$;

do $$
declare
  v_violations text[];
begin
  select array_agg(msg) into v_violations
  from (
    select format('%s does not have SELECT on ecommerce.co_locations', role) as msg
    from unnest(array['anon', 'authenticated']) role
    where not has_table_privilege(role, 'ecommerce.co_locations', 'select')
    union all
    select format('%s has %s on ecommerce.co_locations', role, priv)
    from unnest(array['anon', 'authenticated']) role
    cross join unnest(array['insert', 'update', 'delete']) priv
    where has_table_privilege(role, 'ecommerce.co_locations', priv)
  ) v;

  if v_violations is not null then
    raise exception 'ecommerce.co_locations grant contract broken: %', array_to_string(v_violations, '; ');
  end if;

  if not (
    has_table_privilege('service_role', 'ecommerce.co_locations', 'select')
    and has_table_privilege('service_role', 'ecommerce.co_locations', 'insert')
    and has_table_privilege('service_role', 'ecommerce.co_locations', 'update')
  ) then
    raise exception 'service_role must retain full access to ecommerce.co_locations';
  end if;
end $$;

-- Live-role reproduction: has_table_privilege proves the catalog is right,
-- only an actual query under SET LOCAL ROLE proves what PostgREST's own anon
-- role really sees once RLS is folded in (same reasoning as the email
-- platform contract's finalize-profile-requires-service-role block).
do $$
declare
  v_count integer;
begin
  set local role anon;
  select count(*) into v_count from ecommerce.co_locations where department_code = '05' limit 1;
  reset role;

  if v_count = 0 then
    raise exception 'anon must be able to SELECT ecommerce.co_locations (public DANE data)';
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- Data: the actual DANE Divipola catalog, not just an empty shell -- 33
-- departments, 1,122 municipios, matching this slice's own goal.
-- -----------------------------------------------------------------------------
do $$
declare
  v_row_count integer;
  v_department_count integer;
begin
  select count(*), count(distinct department_code) into v_row_count, v_department_count
  from ecommerce.co_locations;

  if v_row_count <> 1122 then
    raise exception 'Expected 1122 municipios seeded in ecommerce.co_locations, found %', v_row_count;
  end if;

  if v_department_count <> 33 then
    raise exception 'Expected 33 distinct departments in ecommerce.co_locations, found %', v_department_count;
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- D3/D5/D6/D27 (slice S7): shipping_zones, shipping_zone_destinations and
-- shipping_rates exist and are RLS-enabled, closed to anon.
-- -----------------------------------------------------------------------------
do $$
begin
  if to_regclass('ecommerce.shipping_zones') is null then
    raise exception 'Missing ecommerce.shipping_zones';
  end if;
  if to_regclass('ecommerce.shipping_zone_destinations') is null then
    raise exception 'Missing ecommerce.shipping_zone_destinations';
  end if;
  if to_regclass('ecommerce.shipping_rates') is null then
    raise exception 'Missing ecommerce.shipping_rates';
  end if;
end $$;

do $$
declare
  v_missing text[];
begin
  select array_agg(required_column order by required_column) into v_missing
  from (values
    ('shipping_zones', 'store_id'), ('shipping_zones', 'name'),
    ('shipping_zone_destinations', 'zone_id'), ('shipping_zone_destinations', 'store_id'),
    ('shipping_zone_destinations', 'department_code'),
    ('shipping_rates', 'zone_id'), ('shipping_rates', 'basis'), ('shipping_rates', 'amount')
  ) req(required_table, required_column)
  where not exists (
    select 1 from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = req.required_table
      and a.attname = req.required_column
      and a.attnum > 0
      and not a.attisdropped
      and a.attnotnull
  );

  if v_missing is not null then
    raise exception 'Missing NOT NULL columns on shipping zones/rates tables: %', array_to_string(v_missing, ', ');
  end if;
end $$;

-- D3: at most one zone per store may claim a given destination -- the
-- department-only and municipio partial unique indexes, plus the composite
-- FK that keeps a destination's store_id honest against its owning zone.
do $$
begin
  if not exists (
    select 1 from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'shipping_zone_destinations'
      and con.conname = 'shipping_zone_destinations_zone_store_fk' and con.contype = 'f'
  ) then
    raise exception 'Missing ecommerce.shipping_zone_destinations_zone_store_fk';
  end if;

  if not exists (
    select 1 from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'shipping_zone_destinations'
      and con.conname = 'shipping_zone_destinations_municipality_fk' and con.contype = 'f'
  ) then
    raise exception 'Missing ecommerce.shipping_zone_destinations_municipality_fk';
  end if;

  if not exists (
    select 1 from pg_indexes
    where schemaname = 'ecommerce' and tablename = 'shipping_zone_destinations'
      and indexname = 'shipping_zone_destinations_department_key'
  ) then
    raise exception 'Missing unique index ecommerce.shipping_zone_destinations_department_key';
  end if;

  if not exists (
    select 1 from pg_indexes
    where schemaname = 'ecommerce' and tablename = 'shipping_zone_destinations'
      and indexname = 'shipping_zone_destinations_municipality_key'
  ) then
    raise exception 'Missing unique index ecommerce.shipping_zone_destinations_municipality_key';
  end if;
end $$;

-- D6: basis is constrained to the three known values, and a row's bounds
-- must match its basis (flat carries none, ranged rows require range_from).
do $$
begin
  if not exists (
    select 1 from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'shipping_rates'
      and con.conname = 'shipping_rates_basis_chk' and con.contype = 'c'
  ) then
    raise exception 'Missing ecommerce.shipping_rates_basis_chk';
  end if;

  if not exists (
    select 1 from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'shipping_rates'
      and con.conname = 'shipping_rates_bounds_match_basis_chk' and con.contype = 'c'
  ) then
    raise exception 'Missing ecommerce.shipping_rates_bounds_match_basis_chk';
  end if;

  if not exists (
    select 1 from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = 'shipping_rates'
      and con.conname = 'shipping_rates_amount_nonnegative_chk' and con.contype = 'c'
  ) then
    raise exception 'Missing ecommerce.shipping_rates_amount_nonnegative_chk';
  end if;
end $$;

-- D27: RLS enabled on all three, and closed to anon entirely -- the checkout
-- quote (a later slice) reads through service_role, never anon/authenticated
-- directly, same posture as store_shipping_settings.
do $$
declare
  v_missing_rls text[];
begin
  select array_agg(t order by t) into v_missing_rls
  from unnest(array['shipping_zones', 'shipping_zone_destinations', 'shipping_rates']) t
  where not exists (
    select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'ecommerce' and c.relname = t and c.relrowsecurity is true
  );

  if v_missing_rls is not null then
    raise exception 'Missing enabled RLS on: %', array_to_string(v_missing_rls, ', ');
  end if;
end $$;

do $$
declare
  v_violations text[];
begin
  select array_agg(msg) into v_violations
  from (
    select format('anon has %s on ecommerce.%s', priv, tbl) as msg
    from unnest(array['shipping_zones', 'shipping_zone_destinations', 'shipping_rates']) tbl
    cross join unnest(array['select', 'insert', 'update', 'delete']) priv
    where has_table_privilege('anon', format('ecommerce.%s', tbl), priv)
  ) v;

  if v_violations is not null then
    raise exception 'anon must have no access to shipping zones/rates tables: %', array_to_string(v_violations, '; ');
  end if;

  if exists (
    select 1
    from unnest(array['shipping_zones', 'shipping_zone_destinations', 'shipping_rates']) tbl
    cross join unnest(array['select', 'insert', 'update', 'delete']) priv
    where not has_table_privilege('service_role', format('ecommerce.%s', tbl), priv)
  ) then
    raise exception 'service_role must retain full access to shipping zones/rates tables';
  end if;
end $$;
