-- Fail-closed contract verification for OsorIA Ecommerce.
do $$ declare v_missing text[]; begin select array_agg(required_schema) into v_missing from (values ('ecommerce')) req(required_schema) where not exists (select 1 from information_schema.schemata where schema_name=req.required_schema); if v_missing is not null then raise exception 'Missing required schemas: %', array_to_string(v_missing, ', '); end if; end $$;
do $$ declare v_missing text[]; begin select array_agg(format('%s.%s', required_table, required_column) order by required_table, required_column) into v_missing from (values ('store_items','item_description_html'),('store_items','currency_code'),('store_items','inventory_quantity'),('store_items','seo_title'),('store_items','seo_description'),('store_items','tags'),('store_items','primary_image_url'),('store_items','primary_image_alt'),('orders','customer_type'),('orders','customer_first_name'),('orders','customer_last_name'),('orders','payment_method'),('orders','payment_reference'),('orders','shipping_address'),('order_addresses','address_type'),('order_addresses','address_line_1'),('payment_transactions','transaction_type'),('payment_transactions','provider_payment_method'),('payment_transactions','provider_transaction_id'),('payment_transactions','provider_txn_id'),('payment_transactions','metadata'),('payment_transactions','raw_response')) req(required_table,required_column) where not exists (select 1 from information_schema.columns c where c.table_schema='ecommerce' and c.table_name=req.required_table and c.column_name=req.required_column); if v_missing is not null then raise exception 'Missing runtime compatibility columns: %', array_to_string(v_missing, ', '); end if; end $$;
do $$ declare v_missing text[]; begin select array_agg(required_table order by required_table) into v_missing from (values ('app_fonts'),('app_theme_versions'),('app_themes'),('cart_items'),('carts'),('component_styles'),('inventory_movements'),('item_categories'),('item_images'),('item_metrics'),('item_option_values'),('item_options'),('item_seo'),('item_tags'),('item_variants'),('order_addresses'),('order_items'),('orders'),('payment_transactions'),('permissions'),('role_permissions'),('roles'),('shipments'),('store_branding'),('store_commerce_settings'),('store_contact'),('store_integrations'),('store_items'),('store_seo'),('store_seo_keywords'),('store_user_roles'),('store_users'),('stores'),('user_profiles')) req(required_table) where to_regclass(format('ecommerce.%I', req.required_table)) is null; if v_missing is not null then raise exception 'Missing ecommerce tables: %', array_to_string(v_missing, ', '); end if; end $$;
do $$ declare v_missing text[]; begin select array_agg(required_view order by required_view) into v_missing from (values ('app_fonts_legacy'),('app_themes_legacy'),('component_styles_legacy'),('item_options_legacy'),('orders_legacy'),('store_items_legacy'),('stores_legacy')) req(required_view) where to_regclass(format('ecommerce.%I', req.required_view)) is null; if v_missing is not null then raise exception 'Missing ecommerce compatibility views: %', array_to_string(v_missing, ', '); end if; end $$;
do $$ declare v_missing text[]; begin select array_agg(required_function order by required_function) into v_missing from (values ('increment_item_views'),('is_component_styles_admin'),('is_storage_admin')) req(required_function) where not exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='ecommerce' and p.proname=req.required_function); if v_missing is not null then raise exception 'Missing ecommerce functions: %', array_to_string(v_missing, ', '); end if; end $$;
do $$ declare v_missing text[]; begin select array_agg(required_bucket order by required_bucket) into v_missing from (values ('products'),('component-images'),('marketing-assets')) req(required_bucket) where not exists (select 1 from storage.buckets where id=req.required_bucket and public is true); if v_missing is not null then raise exception 'Missing or private ecommerce buckets: %', array_to_string(v_missing, ', '); end if; end $$;
do $$ begin if exists (select 1 from information_schema.tables where table_schema='public' and table_name in ('stores','store_items','orders','component_styles','app_themes','app_fonts')) then raise exception 'Ecommerce-like tables found in public schema. public is not a valid ecommerce target.'; end if; end $$;
select 'ecommerce contract ok' as status;
