-- Curated font pairings (heading + body) on top of ecommerce.app_fonts.
-- Scope: ecommerce schema only.

alter table ecommerce.app_fonts add column if not exists font_axis text;
comment on column ecommerce.app_fonts.font_axis is 'Google Fonts css2 axis fragment, e.g. Inter:wght@400;600;700. Null falls back to the full google_font_url.';

create or replace view ecommerce.app_fonts_legacy as
select id, font_name, css_font_family as font_family, google_font_url as font_url, false as is_system, is_active, created_at, updated_at, null::uuid as store_id, font_axis
from ecommerce.app_fonts;

alter view if exists ecommerce.app_fonts_legacy set (security_invoker = true);
grant select on ecommerce.app_fonts_legacy to anon, authenticated, service_role;

create table if not exists ecommerce.app_font_pairings (
  id bigint generated by default as identity primary key,
  pairing_name text unique not null,
  heading_font_name text not null references ecommerce.app_fonts(font_name),
  body_font_name text not null references ecommerce.app_fonts(font_name),
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists app_font_pairings_single_active on ecommerce.app_font_pairings (is_active) where is_active;

alter table ecommerce.app_font_pairings enable row level security;

revoke all on ecommerce.app_font_pairings from public;
grant select on ecommerce.app_font_pairings to anon, authenticated;
grant insert, update, delete on ecommerce.app_font_pairings to authenticated;
grant all on ecommerce.app_font_pairings to service_role;

drop policy if exists app_font_pairings_public_read on ecommerce.app_font_pairings;
create policy app_font_pairings_public_read on ecommerce.app_font_pairings
for select to anon, authenticated
using (is_active is true or ecommerce.is_global_admin());

drop policy if exists app_font_pairings_admin_insert on ecommerce.app_font_pairings;
create policy app_font_pairings_admin_insert on ecommerce.app_font_pairings
for insert to authenticated
with check (ecommerce.is_global_admin());

drop policy if exists app_font_pairings_admin_update on ecommerce.app_font_pairings;
create policy app_font_pairings_admin_update on ecommerce.app_font_pairings
for update to authenticated
using (ecommerce.is_global_admin())
with check (ecommerce.is_global_admin());

drop policy if exists app_font_pairings_admin_delete on ecommerce.app_font_pairings;
create policy app_font_pairings_admin_delete on ecommerce.app_font_pairings
for delete to authenticated
using (ecommerce.is_global_admin());

-- app_fonts_public_read only exposes is_active rows, but a pairing's heading/body
-- fonts are not themselves is_active (only the pairing is). Without this policy,
-- anon can read the active pairing row but not the fonts it references, so the
-- security_invoker app_font_pairings_legacy join drops the active pairing for anon.
drop policy if exists app_fonts_active_pairing_read on ecommerce.app_fonts;
create policy app_fonts_active_pairing_read on ecommerce.app_fonts
  for select to anon, authenticated
  using (
    font_name in (
      select p.heading_font_name from ecommerce.app_font_pairings p where p.is_active
      union
      select p.body_font_name   from ecommerce.app_font_pairings p where p.is_active
    )
  );

create or replace view ecommerce.app_font_pairings_legacy as
select
  p.id,
  p.pairing_name,
  p.heading_font_name,
  hf.css_font_family as heading_font_family,
  hf.google_font_url as heading_google_font_url,
  hf.font_axis as heading_font_axis,
  p.body_font_name,
  bf.css_font_family as body_font_family,
  bf.google_font_url as body_google_font_url,
  bf.font_axis as body_font_axis,
  p.is_active,
  p.created_at,
  p.updated_at
from ecommerce.app_font_pairings p
join ecommerce.app_fonts hf on hf.font_name = p.heading_font_name
join ecommerce.app_fonts bf on bf.font_name = p.body_font_name;

alter view if exists ecommerce.app_font_pairings_legacy set (security_invoker = true);
grant select on ecommerce.app_font_pairings_legacy to anon, authenticated, service_role;

-- #2339 reconciliation: 'Inter' (default body font) was hand-inserted on staging,
-- but no migration creates it, so a fresh db push/reset failed the app_font_pairings
-- FK below (body_font_name='Inter'). Upsert makes the chain self-contained for new
-- projects and stays a no-op on staging (where 'Inter' already exists).
insert into ecommerce.app_fonts (font_name, font_family, font_display_name, google_font_url, css_font_family, font_axis, is_active)
values ('Inter', '"Inter", sans-serif', 'Inter', 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap', '"Inter", sans-serif', 'Inter:wght@400;500;600', true)
on conflict (font_name) do update set font_axis = excluded.font_axis;

insert into ecommerce.app_fonts (font_name, font_family, font_display_name, google_font_url, css_font_family, font_axis, is_active)
values
  ('Space Grotesk', '"Space Grotesk", sans-serif', 'Space Grotesk', 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;700&display=swap', '"Space Grotesk", sans-serif', 'Space+Grotesk:wght@500;700', false),
  ('Sora', '"Sora", sans-serif', 'Sora', 'https://fonts.googleapis.com/css2?family=Sora:wght@500;700&display=swap', '"Sora", sans-serif', 'Sora:wght@500;700', false),
  ('Outfit', '"Outfit", sans-serif', 'Outfit', 'https://fonts.googleapis.com/css2?family=Outfit:wght@500;700&display=swap', '"Outfit", sans-serif', 'Outfit:wght@500;700', false),
  ('Archivo', '"Archivo", sans-serif', 'Archivo', 'https://fonts.googleapis.com/css2?family=Archivo:wght@600;700&display=swap', '"Archivo", sans-serif', 'Archivo:wght@600;700', false),
  ('Bricolage Grotesque', '"Bricolage Grotesque", sans-serif', 'Bricolage Grotesque', 'https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:wght@600;700&display=swap', '"Bricolage Grotesque", sans-serif', 'Bricolage+Grotesque:wght@600;700', false),
  ('IBM Plex Sans', '"IBM Plex Sans", sans-serif', 'IBM Plex Sans', 'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600&display=swap', '"IBM Plex Sans", sans-serif', 'IBM+Plex+Sans:wght@400;500;600', false),
  ('DM Sans', '"DM Sans", sans-serif', 'DM Sans', 'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap', '"DM Sans", sans-serif', 'DM+Sans:wght@400;500;700', false),
  ('Work Sans', '"Work Sans", sans-serif', 'Work Sans', 'https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;500;600&display=swap', '"Work Sans", sans-serif', 'Work+Sans:wght@400;500;600', false),
  ('Manrope', '"Manrope", sans-serif', 'Manrope', 'https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600&display=swap', '"Manrope", sans-serif', 'Manrope:wght@400;500;600', false)
on conflict (font_name) do nothing;

insert into ecommerce.app_font_pairings (pairing_name, heading_font_name, body_font_name, is_active)
values
  ('space-grotesk-inter', 'Space Grotesk', 'Inter', true),
  ('sora-ibm-plex', 'Sora', 'IBM Plex Sans', false),
  ('outfit-dm-sans', 'Outfit', 'DM Sans', false),
  ('archivo-work-sans', 'Archivo', 'Work Sans', false),
  ('bricolage-manrope', 'Bricolage Grotesque', 'Manrope', false)
on conflict (pairing_name) do nothing;
