-- Idempotent patch for existing ecommerce schemas. Scope: ecommerce.* only.
create extension if not exists pgcrypto with schema extensions;
alter table if exists ecommerce.store_items add column if not exists item_description_html text, add column if not exists currency_code varchar not null default 'COP', add column if not exists inventory_quantity integer default 0, add column if not exists seo_title varchar, add column if not exists seo_description text, add column if not exists tags varchar[] default array[]::varchar[], add column if not exists primary_image_url text, add column if not exists primary_image_alt text;
alter table if exists ecommerce.orders add column if not exists customer_type varchar default 'guest', add column if not exists customer_first_name varchar, add column if not exists customer_last_name varchar, add column if not exists customer_phone varchar, add column if not exists shipping_address varchar, add column if not exists shipping_city varchar, add column if not exists shipping_postal_code varchar, add column if not exists shipping_country varchar, add column if not exists shipping_notes varchar, add column if not exists payment_method varchar, add column if not exists payment_reference varchar;
alter table if exists ecommerce.order_addresses add column if not exists address_type text default 'shipping', add column if not exists address_line_1 text, add column if not exists city varchar, add column if not exists postal_code varchar, add column if not exists country varchar default 'Colombia', add column if not exists created_at timestamptz default now(), add column if not exists updated_at timestamptz default now();
alter table if exists ecommerce.payment_transactions add column if not exists transaction_type varchar default 'payment', add column if not exists provider_payment_method varchar, add column if not exists provider_transaction_id varchar, add column if not exists provider_txn_id varchar, add column if not exists metadata jsonb default '{}'::jsonb, add column if not exists raw_response jsonb;
update ecommerce.payment_transactions set provider_transaction_id = coalesce(provider_transaction_id, provider_txn_id) where provider_transaction_id is null;
update ecommerce.payment_transactions set provider_txn_id = coalesce(provider_txn_id, provider_transaction_id) where provider_txn_id is null;
do $$ begin
  if exists (select 1 from information_schema.columns where table_schema='ecommerce' and table_name='order_addresses' and column_name='addr_type') then alter table ecommerce.order_addresses alter column addr_type drop not null; update ecommerce.order_addresses set address_type=coalesce(address_type,addr_type::text); end if;
  if exists (select 1 from information_schema.columns where table_schema='ecommerce' and table_name='order_addresses' and column_name='address_line1') then alter table ecommerce.order_addresses alter column address_line1 drop not null; update ecommerce.order_addresses set address_line_1=coalesce(address_line_1,address_line1); end if;
  if exists (select 1 from information_schema.columns where table_schema='ecommerce' and table_name='order_addresses' and column_name='first_name') then alter table ecommerce.order_addresses alter column first_name drop not null; alter table ecommerce.order_addresses alter column first_name set default ''; end if;
  if exists (select 1 from information_schema.columns where table_schema='ecommerce' and table_name='order_addresses' and column_name='last_name') then alter table ecommerce.order_addresses alter column last_name drop not null; alter table ecommerce.order_addresses alter column last_name set default ''; end if;
end $$;
create unique index if not exists component_styles_store_component_unique on ecommerce.component_styles(store_id, component_name);
create unique index if not exists store_items_store_code_unique on ecommerce.store_items(store_id, item_code) where item_code is not null;
create unique index if not exists store_items_store_slug_unique on ecommerce.store_items(store_id, item_slug) where item_slug is not null;
