-- Editable shop: per-store /shop configuration (default sort + which filter
-- controls are visible). One row per store; a missing row means the store
-- hasn't customized its shop yet, so the read path falls back to the default
-- config (see lib/shop/shop-config.ts). Copy (title/subtitle) is NOT stored
-- here — it lives in ecommerce.component_styles under component_name 'shop'.
-- Scope: ecommerce schema only.

create table if not exists ecommerce.shop_config (
  id bigint generated by default as identity primary key,
  store_id uuid not null references ecommerce.stores(id) on delete cascade,
  config jsonb not null default '{}'::jsonb,
  updated_at timestamptz default now(),
  unique (store_id)
);

alter table ecommerce.shop_config enable row level security;

drop policy if exists shop_config_public_read on ecommerce.shop_config;
create policy shop_config_public_read on ecommerce.shop_config
for select to anon, authenticated
using (ecommerce.is_public_store(store_id) or ecommerce.can_manage_store(store_id));

drop policy if exists shop_config_admin_write on ecommerce.shop_config;
create policy shop_config_admin_write on ecommerce.shop_config
for all to authenticated
using (ecommerce.can_manage_store(store_id))
with check (ecommerce.can_manage_store(store_id));

revoke all on ecommerce.shop_config from public;
grant select on ecommerce.shop_config to anon, authenticated;
grant insert, update, delete on ecommerce.shop_config to authenticated;
grant all on ecommerce.shop_config to service_role;
