-- Composable home: per-store section order/visibility for the composable
-- home sections (hero, popular, products, featured, specialOffer, whyus,
-- newsletter). `footer` is fixed chrome and never lives here. One row per
-- store; a missing row means the store hasn't customized its layout yet, so
-- the read path falls back to the default order (see
-- lib/sections/home-composition.ts).
-- Scope: ecommerce schema only.

create table if not exists ecommerce.home_section_layout (
  id bigint generated by default as identity primary key,
  store_id uuid not null references ecommerce.stores(id) on delete cascade,
  sections jsonb not null,
  updated_at timestamptz default now(),
  unique (store_id)
);

alter table ecommerce.home_section_layout enable row level security;

drop policy if exists home_section_layout_public_read on ecommerce.home_section_layout;
create policy home_section_layout_public_read on ecommerce.home_section_layout
for select to anon, authenticated
using (ecommerce.is_public_store(store_id) or ecommerce.can_manage_store(store_id));

drop policy if exists home_section_layout_admin_write on ecommerce.home_section_layout;
create policy home_section_layout_admin_write on ecommerce.home_section_layout
for all to authenticated
using (ecommerce.can_manage_store(store_id))
with check (ecommerce.can_manage_store(store_id));

revoke all on ecommerce.home_section_layout from public;
grant select on ecommerce.home_section_layout to anon, authenticated;
grant insert, update, delete on ecommerce.home_section_layout to authenticated;
grant all on ecommerce.home_section_layout to service_role;
