-- Ecommerce-owned storage only. Do not mirror unrelated buckets from polluted projects.
insert into storage.buckets (id, name, public) values ('products','products',true), ('component-images','component-images',true) on conflict (id) do update set name=excluded.name, public=excluded.public;
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values ('marketing-assets','marketing-assets',true,5242880,array['image/jpeg','image/jpg','image/png','image/webp','image/gif']::text[]) on conflict (id) do update set name=excluded.name, public=excluded.public, file_size_limit=excluded.file_size_limit, allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "Storage public read products" on storage.objects; create policy "Storage public read products" on storage.objects for select to public using (bucket_id='products');
drop policy if exists "Storage public read component-images" on storage.objects; create policy "Storage public read component-images" on storage.objects for select to public using (bucket_id='component-images');
drop policy if exists marketing_assets_public_read on storage.objects; create policy marketing_assets_public_read on storage.objects for select to public using (bucket_id='marketing-assets');
drop policy if exists "Storage admin upload products" on storage.objects; create policy "Storage admin upload products" on storage.objects for insert to authenticated with check (bucket_id='products' and ecommerce.is_storage_admin());
drop policy if exists "Storage admin update products" on storage.objects; create policy "Storage admin update products" on storage.objects for update to authenticated using (bucket_id='products' and ecommerce.is_storage_admin()) with check (bucket_id='products' and ecommerce.is_storage_admin());
drop policy if exists "Storage admin delete products" on storage.objects; create policy "Storage admin delete products" on storage.objects for delete to authenticated using (bucket_id='products' and ecommerce.is_storage_admin());
drop policy if exists "Storage admin upload component-images" on storage.objects; create policy "Storage admin upload component-images" on storage.objects for insert to authenticated with check (bucket_id='component-images' and ecommerce.is_storage_admin());
drop policy if exists "Storage admin update component-images" on storage.objects; create policy "Storage admin update component-images" on storage.objects for update to authenticated using (bucket_id='component-images' and ecommerce.is_storage_admin()) with check (bucket_id='component-images' and ecommerce.is_storage_admin());
drop policy if exists "Storage admin delete component-images" on storage.objects; create policy "Storage admin delete component-images" on storage.objects for delete to authenticated using (bucket_id='component-images' and ecommerce.is_storage_admin());
drop policy if exists marketing_assets_admin_insert on storage.objects; create policy marketing_assets_admin_insert on storage.objects for insert to authenticated with check (bucket_id='marketing-assets' and ecommerce.is_storage_admin());
drop policy if exists marketing_assets_admin_update on storage.objects; create policy marketing_assets_admin_update on storage.objects for update to authenticated using (bucket_id='marketing-assets' and ecommerce.is_storage_admin()) with check (bucket_id='marketing-assets' and ecommerce.is_storage_admin());
drop policy if exists marketing_assets_admin_delete on storage.objects; create policy marketing_assets_admin_delete on storage.objects for delete to authenticated using (bucket_id='marketing-assets' and ecommerce.is_storage_admin());
